"""LQ-044 — ergänzende CLI-Output-/Validierungs-Regressionstests.

Diese Tests schreiben ausschließlich das BESTEHENDE Verhalten der lokalen CLI
``src/liquent/cli/backtest_mid_breakout.py`` fest (Behavior-Lock). Keine
Produktionslogik-Änderung, keine neuen Features, keine Änderung bestehender
CLI-Tests. Aufrufe in-process über ``main(argv)``; Datei-Outputs ausschließlich
in ``tmp_path``; es werden nur die vorhandenen synthetischen Fixtures gelesen.

Abgedeckt werden bisher nicht explizit auf CLI-Ebene gesicherte Grenzen
(siehe ``docs/lq-044-cli-output-polish.md``, Test Plan): CLI-Range-Rejects,
Bool-Parsing, Exit-Code-Trichotomie, Output-Framing, Parent-Dir-Anlage,
Terminal-/Error-Ausgabe.
"""

from pathlib import Path

from liquent.cli.backtest_mid_breakout import main

_FIXTURES = Path(__file__).parent / "fixtures"
_CSV = str(_FIXTURES / "strategy_mid_breakout_long.csv")


def _args(output: Path, *extra: str) -> list[str]:
    return ["--csv", _CSV, "--output", str(output), *extra]


# --------------------------------------------------------------------------- #
# Validierungs-Rejects (Exit 2) auf CLI-Ebene (_validate_ranges)
# --------------------------------------------------------------------------- #
def test_initial_equity_non_positive_exit2(tmp_path):
    out = tmp_path / "r.md"
    assert main(_args(out, "--initial-equity", "0")) == 2
    assert not out.exists()


def test_lookback_bars_non_positive_exit2(tmp_path):
    out = tmp_path / "r.md"
    assert main(_args(out, "--lookback-bars", "0")) == 2
    assert not out.exists()


def test_stop_distance_pct_out_of_range_exit2(tmp_path):
    out = tmp_path / "r.md"
    assert main(_args(out, "--stop-distance-pct", "0")) == 2
    assert main(_args(out, "--stop-distance-pct", "1.0")) == 2
    assert not out.exists()


def test_max_position_size_non_positive_exit2(tmp_path):
    out = tmp_path / "r.md"
    assert main(_args(out, "--max-position-size", "0")) == 2
    assert not out.exists()


def test_max_total_exposure_non_positive_exit2(tmp_path):
    out = tmp_path / "r.md"
    assert main(_args(out, "--max-total-exposure", "0")) == 2
    assert not out.exists()


def test_max_daily_drawdown_non_positive_exit2(tmp_path):
    out = tmp_path / "r.md"
    assert main(_args(out, "--max-daily-drawdown", "0")) == 2
    assert not out.exists()


# --------------------------------------------------------------------------- #
# Bool-Parsing
# --------------------------------------------------------------------------- #
def test_allow_short_accepts_known_forms(tmp_path):
    for i, value in enumerate(("true", "false", "1", "0", "yes", "no", "TRUE", "No")):
        out = tmp_path / f"r_{i}.md"
        assert main(_args(out, "--allow-short", value)) == 0, f"--allow-short {value!r}"
        assert out.is_file()


def test_invalid_allow_short_value_exit2(tmp_path):
    out = tmp_path / "r.md"
    assert main(_args(out, "--allow-short", "maybe")) == 2
    assert not out.exists()


# --------------------------------------------------------------------------- #
# Exit-Code-Trichotomie
# --------------------------------------------------------------------------- #
def test_exit_code_trichotomy(tmp_path):
    # Validierung/Usage -> 2
    bad = tmp_path / "bad.md"
    assert main(_args(bad, "--initial-equity", "0")) == 2
    # fehlende CSV -> 1
    miss = tmp_path / "miss.md"
    assert main(["--csv", str(tmp_path / "nope.csv"), "--output", str(miss)]) == 1
    # vorhandenes Output ohne --overwrite -> 1
    exists = tmp_path / "exists.md"
    exists.write_text("ORIGINAL", encoding="utf-8")
    assert main(_args(exists)) == 1
    assert exists.read_text(encoding="utf-8") == "ORIGINAL"
    # Erfolg -> 0
    ok = tmp_path / "ok.md"
    assert main(_args(ok)) == 0
    assert ok.is_file()


# --------------------------------------------------------------------------- #
# Output-Framing / File-Output
# --------------------------------------------------------------------------- #
def test_report_framing_disclaimer_blank_line_and_trailing_newline(tmp_path):
    out = tmp_path / "r.md"
    assert main(_args(out)) == 0
    text = out.read_text(encoding="utf-8")
    lines = text.split("\n")
    assert lines[0].startswith("<!-- Generated by Liquent local CLI.")
    assert lines[1] == ""  # Leerzeile nach dem Disclaimer
    assert text.endswith("\n")


def test_creates_missing_output_parent_dirs(tmp_path):
    out = tmp_path / "sub" / "deep" / "report.md"
    assert main(_args(out)) == 0
    assert out.is_file()


# --------------------------------------------------------------------------- #
# Terminal- / Error-Ausgabe
# --------------------------------------------------------------------------- #
def test_stdout_contains_report_written_line(tmp_path, capsys):
    out = tmp_path / "r.md"
    assert main(_args(out)) == 0
    captured = capsys.readouterr().out
    assert "report written:" in captured


def test_error_goes_to_stderr_without_traceback(tmp_path, capsys):
    out = tmp_path / "r.md"
    assert main(_args(out, "--initial-equity", "0")) == 2
    err = capsys.readouterr().err
    assert "error:" in err
    assert "Traceback" not in err
