import hashlib,json
from pathlib import Path
import pytest
import liquent_platform.operators.disposable_postgres_cleanup_generation_continue as generation
import liquent_platform.operators.disposable_postgres_cleanup_generation_continue_reconcile as inspect
import liquent_platform.operators.disposable_postgres_cleanup_generation_continue_finalize as final
from tests.test_lq331_disposable_postgres_reconciliation import NOW
from tests.test_lq341_disposable_postgres_cleanup_reconciliation import Processes,_private
from tests.test_lq380_disposable_postgres_cleanup_generation_lineage_finalization import prepare
def finalized_three(tmp_path:Path):
    values,cleanup,_=prepare(tmp_path);original=final.reconcile_disposable_postgres_cleanup_generation_continuation;final.reconcile_disposable_postgres_cleanup_generation_continuation=lambda **_:(json.dumps({"operation":"disposable_postgres_cleanup_generation_continuation_reconciliation","outcome":"generation_continuation_not_started","schema_version":1},sort_keys=True,separators=(",",":"))+"\n").encode()
    try:final.finalize_disposable_postgres_cleanup_generation_continuation(**values)
    finally:final.reconcile_disposable_postgres_cleanup_generation_continuation=original
    values["generation_lineage_continuation_files"].append(values["generation_continuation_file"]);values["generation_lineage_finalization_files"].append(values["generation_finalization_file"]);return values,cleanup
def continuation(values,tmp_path:Path,number):
    previous_path=values["generation_lineage_continuation_files"][-1];last_path=values["generation_lineage_finalization_files"][-1];previous=json.loads(previous_path.read_text());last=json.loads(last_path.read_text());stem=hashlib.sha256(last["generation_finalization_id"].encode()).hexdigest();evidence=values["evidence_directory"]/f"postgres-cleanup-generation-continuation-finalization-{stem}.json";auth={"schema_version":1,"generation_continuation_id":f"generation-continuation-382-{number}","generation":number,"predecessor_kind":"repeatable_generation","predecessor_generation":number-1,**{k:last[k] for k in generation.ROOT},"predecessor_resume_from":previous["resume_from"],"predecessor_finalization_authorization_sha256":hashlib.sha256(last_path.read_bytes()).hexdigest(),"predecessor_finalization_evidence_sha256":hashlib.sha256(evidence.read_bytes()).hexdigest(),"operation":"continue_disposable_postgres_cleanup_from_generation","scope":"runtime_only","resume_from":previous["resume_from"],"executor_id":f"generation-{number}-executor","authorizer_id":f"generation-{number}-authorizer","valid_from":"2026-08-20T13:30:00Z","valid_until":"2026-08-20T14:30:00Z"};return _private(tmp_path/f"generation-{number}.json",auth),auth
def authorizations(values,tmp_path:Path,continuation_path,auth,number):
    reconciliation={"schema_version":1,"generation_reconciliation_id":f"generation-reconciliation-382-{number}",**{k:auth[k] for k in inspect.COMPARE},"generation_continuation_authorization_sha256":hashlib.sha256(continuation_path.read_bytes()).hexdigest(),"operation":"inspect_disposable_postgres_cleanup_generation_continuation","scope":"runtime_only","executor_id":f"generation-{number}-inspector","authorizer_id":f"generation-{number}-inspection-authorizer","valid_from":"2026-08-20T13:30:00Z","valid_until":"2026-08-20T14:30:00Z"};reconciliation_path=_private(tmp_path/f"generation-{number}-reconciliation.json",reconciliation);finalization={"schema_version":1,"generation_finalization_id":f"generation-finalization-382-{number}",**{k:reconciliation[k] for k in final.HIST},"generation_reconciliation_authorization_sha256":hashlib.sha256(reconciliation_path.read_bytes()).hexdigest(),"operation":"finalize_disposable_postgres_cleanup_generation_continuation","scope":"runtime_only","executor_id":f"generation-{number}-finalizer","authorizer_id":f"generation-{number}-finalization-authorizer","valid_from":"2026-08-20T13:30:00Z","valid_until":"2026-08-20T14:30:00Z"};finalization_path=_private(tmp_path/f"generation-{number}-finalization.json",finalization);return reconciliation_path,reconciliation,finalization_path,finalization
def result(operation,outcome):return (json.dumps({"operation":operation,"outcome":outcome,"schema_version":1},sort_keys=True,separators=(",",":"))+"\n").encode()
def test_generation_four_runs_continuation_inspector_and_finalizer(tmp_path,monkeypatch):
    values,cleanup=finalized_three(tmp_path);current_path,current=continuation(values,tmp_path,4);common={**values,"generation_continuation_file":current_path,"clock":lambda:NOW,"processes":Processes([])};common.pop("generation_reconciliation_file");common.pop("generation_finalization_file");monkeypatch.setattr(generation,"reconcile_disposable_postgres_cleanup",lambda **_:result("disposable_postgres_runtime_cleanup_reconciliation",current["resume_from"]))
    with pytest.raises(generation.DisposablePostgresCleanupGenerationContinueUnavailable):generation.continue_disposable_postgres_cleanup_generation(**common)
    reconciliation_path,_,finalization_path,_=authorizations(values,tmp_path,current_path,current,4);inspector={**common,"generation_reconciliation_file":reconciliation_path};monkeypatch.setattr(inspect,"reconcile_disposable_postgres_cleanup",lambda **_:result("disposable_postgres_runtime_cleanup_reconciliation",current["resume_from"]));assert json.loads(inspect.reconcile_disposable_postgres_cleanup_generation_continuation(**inspector))["outcome"]=="generation_continuation_not_started"
    finalizer={**inspector,"generation_finalization_file":finalization_path};monkeypatch.setattr(final,"reconcile_disposable_postgres_cleanup_generation_continuation",lambda **_:result("disposable_postgres_cleanup_generation_continuation_reconciliation","generation_continuation_not_started"));assert json.loads(final.finalize_disposable_postgres_cleanup_generation_continuation(**finalizer))["outcome"]=="generation_continuation_attempt_finalized" and cleanup.exists()
def test_generation_seventeen_accepts_complete_sixteen_pair_lineage(tmp_path):
    values,_=finalized_three(tmp_path)
    for number in range(4,17):
        continuation_path,auth=continuation(values,tmp_path,number);_,_,finalization_path,finalization=authorizations(values,tmp_path,continuation_path,auth,number);binding=final._binding5(finalization,finalization_path);stem=hashlib.sha256(finalization["generation_finalization_id"].encode()).hexdigest();_private(values["evidence_directory"]/f"postgres-cleanup-generation-continuation-finalization-{stem}.json",dict(binding,observed_state="generation_continuation_not_started",outcome="generation_continuation_attempt_finalized",started_at="2026-08-20T14:00:00Z",completed_at="2026-08-20T14:01:00Z"));values["generation_lineage_continuation_files"].append(continuation_path);values["generation_lineage_finalization_files"].append(finalization_path)
    current_path,current=continuation(values,tmp_path,17);previous,last,evidence,out=generation._lineage(current,values["generation_lineage_continuation_files"],values["generation_lineage_finalization_files"],values["chained_finalization_file"],values["evidence_directory"],values["project_name"]);assert len(values["generation_lineage_continuation_files"])==generation.MAX_LINEAGE and previous["generation"]==16 and last["generation"]==16 and evidence.exists() and out=="generation_continuation_attempt_finalized" and current_path.exists()
