import hashlib,json
from pathlib import Path
import liquent_platform.operators.disposable_postgres_cleanup_generation_continue_finalize as generation_final
import liquent_platform.operators.disposable_postgres_cleanup_finalize as cleanup_final
from tests.test_lq331_disposable_postgres_reconciliation import NOW
from tests.test_lq341_disposable_postgres_cleanup_reconciliation import _private
from tests.test_lq380_disposable_postgres_cleanup_generation_lineage_finalization import prepare
def result(operation,outcome):return (json.dumps({"operation":operation,"outcome":outcome,"schema_version":1},sort_keys=True,separators=(",",":"))+"\n").encode()
def cleanup_authorization(values,tmp_path:Path):
    previous=json.loads(values["cleanup_reconciliation_file"].read_text());authorization={"schema_version":1,"cleanup_finalization_id":"cleanup-finalization-384","cleanup_reconciliation_id":previous["cleanup_reconciliation_id"],"cleanup_id":previous["cleanup_id"],"run_id":previous["run_id"],"phase":"disposable_postgres","source_commit":previous["source_commit"],"image_ref":previous["image_ref"],"compose_sha256":previous["compose_sha256"],"reconciliation_id":previous["reconciliation_id"],"claim_reconciliation_id":previous["claim_reconciliation_id"],"disposition_id":previous["disposition_id"],"staging_evidence_sha256":previous["staging_evidence_sha256"],"reconciliation_evidence_sha256":previous["reconciliation_evidence_sha256"],"claim_reconciliation_evidence_sha256":previous["claim_reconciliation_evidence_sha256"],"disposition_authorization_sha256":previous["disposition_authorization_sha256"],"cleanup_authorization_sha256":previous["cleanup_authorization_sha256"],"cleanup_reconciliation_authorization_sha256":hashlib.sha256(values["cleanup_reconciliation_file"].read_bytes()).hexdigest(),"operation":"finalize_disposable_postgres_runtime_cleanup","scope":"runtime_only","executor_id":"cleanup-handoff-executor","authorizer_id":"cleanup-handoff-authorizer","valid_from":"2026-08-20T13:30:00Z","valid_until":"2026-08-20T14:30:00Z"};return _private(tmp_path/"cleanup-handoff-finalization.json",authorization)
def lineage_snapshot(values):
    paths=[*values["generation_lineage_continuation_files"],*values["generation_lineage_finalization_files"],values["generation_continuation_file"],values["generation_reconciliation_file"],values["generation_finalization_file"],*sorted(values["evidence_directory"].glob("postgres-cleanup-generation-*.json"))];return {path:path.read_bytes() for path in paths}
def test_terminal_generation_handoff_writes_cleanup_evidence_before_releasing_only_cleanup_claim(tmp_path,monkeypatch):
    values,cleanup_claim,generation_claim=prepare(tmp_path);generation_calls=[]
    def generation_inspect(**_):generation_calls.append("runtime_removed_evidence_missing");return result("disposable_postgres_cleanup_generation_continuation_reconciliation","runtime_removed_evidence_missing")
    monkeypatch.setattr(generation_final,"reconcile_disposable_postgres_cleanup_generation_continuation",generation_inspect);assert json.loads(generation_final.finalize_disposable_postgres_cleanup_generation_continuation(**values))["outcome"]=="runtime_removal_ready_for_cleanup_finalization" and not generation_claim.exists() and cleanup_claim.exists() and generation_calls==["runtime_removed_evidence_missing"]
    before=lineage_snapshot(values);cleanup_file=cleanup_authorization(values,tmp_path);cleanup_values={key:values[key] for key in ("docker_executable","authorization_file","reconciliation_file","claim_reconciliation_file","disposition_file","cleanup_file","cleanup_reconciliation_file","staging_evidence_file","compose_file","runtime_environment_file","image_environment_file","project_name","evidence_directory","processes")};cleanup_values.update(cleanup_finalization_file=cleanup_file,clock=lambda:NOW);inspection_calls=[];monkeypatch.setattr(cleanup_final,"reconcile_disposable_postgres_cleanup",lambda **_:(inspection_calls.append("runtime_removed_evidence_missing") or result("disposable_postgres_runtime_cleanup_reconciliation","runtime_removed_evidence_missing")));expected=values["evidence_directory"]/f"postgres-cleanup-finalization-{hashlib.sha256(b'cleanup-finalization-384').hexdigest()}.json";release=cleanup_final._release_claim
    def checked_release(path,binding,root_descriptor):assert expected.exists() and path==cleanup_claim;return release(path,binding,root_descriptor)
    monkeypatch.setattr(cleanup_final,"_release_claim",checked_release);assert json.loads(cleanup_final.finalize_disposable_postgres_cleanup(**cleanup_values))["outcome"]=="runtime_removal_finalized" and inspection_calls==["runtime_removed_evidence_missing"] and expected.exists() and not cleanup_claim.exists() and lineage_snapshot(values)==before
