"""Tests für das lokale CLI ``backtest_mid_breakout`` (LQ-007 Phase 2b).

In-process über ``main(argv)`` — kein Subprozess, kein Netzwerk. Nutzt
``tmp_path`` für die Ausgabe und die bestehenden synthetischen Fixtures. Reine
Analyse, keine echten Daten, keine Zugangsdaten.
"""

from pathlib import Path

from liquent.cli.backtest_mid_breakout import main

_FIXTURES = Path(__file__).parent / "fixtures"


def _fixture(name: str) -> str:
    return str(_FIXTURES / name)


def _args(csv_name: str, output: Path, *extra: str) -> list[str]:
    return [
        "--csv", _fixture(csv_name),
        "--output", str(output),
        "--symbol", "TESTUSDT",
        "--exchange", "synthetic",
        "--asset-class", "crypto",
        *extra,
    ]


# 1: Long-Fixture -> Exit 0, nicht-leere Markdown-Datei.
def test_long_fixture_writes_markdown(tmp_path):
    out = tmp_path / "report.md"
    rc = main(_args("strategy_mid_breakout_long.csv", out))
    assert rc == 0
    assert out.is_file()
    assert out.read_text(encoding="utf-8").strip() != ""


# 2: Markdown enthält die erwarteten Felder/Werte.
def test_markdown_contains_expected_fields(tmp_path):
    out = tmp_path / "report.md"
    assert main(_args("strategy_mid_breakout_long.csv", out)) == 0
    text = out.read_text(encoding="utf-8")
    for token in (
        "MidBreakoutStrategy",
        "sizing_mode",
        "percent_risk",
        "data_symbol",
        "TESTUSDT",
        "data_history_meets_minimum",
    ):
        assert token in text, f"Report muss {token!r} enthalten"
    # Disclaimer-Kopf ist vorhanden.
    assert text.startswith("<!-- Generated by Liquent local CLI.")


# 3: Fehlende CSV -> Exit != 0, keine Output-Datei.
def test_missing_csv_fails(tmp_path):
    out = tmp_path / "report.md"
    rc = main([
        "--csv", _fixture("does_not_exist.csv"),
        "--output", str(out),
    ])
    assert rc != 0
    assert not out.exists()


# 4: Ungültiger timeframe -> Exit != 0.
def test_invalid_timeframe_fails(tmp_path):
    out = tmp_path / "report.md"
    rc = main(_args("strategy_mid_breakout_long.csv", out, "--timeframe", "3m"))
    assert rc != 0
    assert not out.exists()


# 5: Ungültiges risk_per_trade_pct -> Exit != 0 (zu groß und zu klein).
def test_invalid_risk_per_trade_pct_fails(tmp_path):
    out = tmp_path / "report.md"
    assert main(_args("strategy_mid_breakout_long.csv", out, "--risk-per-trade-pct", "1.5")) != 0
    assert main(_args("strategy_mid_breakout_long.csv", out, "--risk-per-trade-pct", "0")) != 0
    assert not out.exists()


# 6: Existierender Output ohne --overwrite -> Exit != 0, Datei unverändert.
def test_no_overwrite_keeps_existing(tmp_path):
    out = tmp_path / "report.md"
    out.write_text("ORIGINAL", encoding="utf-8")
    rc = main(_args("strategy_mid_breakout_long.csv", out))
    assert rc != 0
    assert out.read_text(encoding="utf-8") == "ORIGINAL"


# 7: Mit --overwrite -> Exit 0, Datei wird überschrieben.
def test_overwrite_replaces_existing(tmp_path):
    out = tmp_path / "report.md"
    out.write_text("ORIGINAL", encoding="utf-8")
    rc = main(_args("strategy_mid_breakout_long.csv", out, "--overwrite"))
    assert rc == 0
    assert out.read_text(encoding="utf-8") != "ORIGINAL"
    assert "MidBreakoutStrategy" in out.read_text(encoding="utf-8")


# 8: No-Signal-Fixture -> Exit 0, Report mit number_of_trades.
def test_no_signal_fixture_writes_report(tmp_path):
    out = tmp_path / "report.md"
    rc = main(_args("strategy_mid_breakout_no_signal.csv", out))
    assert rc == 0
    text = out.read_text(encoding="utf-8")
    assert "number_of_trades" in text
    assert "Number of Trades: 0" in text


# 9: Determinismus -> zweimaliger Lauf liefert byte-identischen Output.
def test_deterministic_output(tmp_path):
    out_a = tmp_path / "a.md"
    out_b = tmp_path / "b.md"
    assert main(_args("strategy_mid_breakout_long.csv", out_a)) == 0
    assert main(_args("strategy_mid_breakout_long.csv", out_b)) == 0
    assert out_a.read_bytes() == out_b.read_bytes()


# 10: Statischer Scan des CLI-Moduls — keine Netzwerk-/Exchange-/Credential-
#     /Live-/Paper-/Marketing-Pfade. Verbotsbegriffe aus Fragmenten, damit die
#     Liste sich nicht selbst trifft.
def test_cli_module_has_no_forbidden_paths_or_terms():
    import inspect

    from liquent.cli import backtest_mid_breakout as module

    source_code = inspect.getsource(module).lower()
    forbidden = [
        "soc" + "ket",
        "url" + "lib",
        "req" + "uests",
        "ht" + "tp://",
        "ht" + "tps://",
        "web" + "soc" + "ket",
        "cc" + "xt",
        "live_" + "order",
        "place_" + "order",
        "paper_" + "trading",
        "api_" + "key",
        "sec" + "ret",
        "pass" + "word",
        "profit" + "abel",
        "garan" + "tiert",
        "live-" + "ready",
        "sicherer " + "gewinn",
        "empfehlung " + "kaufen",
        "profit" + "able",
        "guaran" + "teed",
    ]
    for token in forbidden:
        assert token not in source_code, f"CLI-Modul darf {token!r} nicht enthalten"


# --------------------------------------------------------------------------- #
# LQ-007 Phase 4c: --gap-policy / --max-gaps gegen die Gap-Fixture
# --------------------------------------------------------------------------- #
# ohlcv_gap_5m.csv hat bei timeframe=5m genau eine Lücke (00:05 -> 00:15).
_GAP_FIXTURE = "ohlcv_gap_5m.csv"


# 11: --gap-policy reject -> Exit != 0, keine Output-Datei.
def test_gap_reject_fails(tmp_path):
    out = tmp_path / "report.md"
    rc = main(_args(_GAP_FIXTURE, out, "--gap-policy", "reject"))
    assert rc != 0
    assert not out.exists()


# 12: --gap-policy flag -> Exit 0, Report wird erzeugt.
def test_gap_flag_writes_report(tmp_path):
    out = tmp_path / "report.md"
    rc = main(_args(_GAP_FIXTURE, out, "--gap-policy", "flag"))
    assert rc == 0
    assert out.is_file()
    assert "MidBreakoutStrategy" in out.read_text(encoding="utf-8")


# 13: --gap-policy tolerate --max-gaps 1 -> Exit 0, Report wird erzeugt.
def test_gap_tolerate_within_max_gaps(tmp_path):
    out = tmp_path / "report.md"
    rc = main(_args(_GAP_FIXTURE, out, "--gap-policy", "tolerate", "--max-gaps", "1"))
    assert rc == 0
    assert out.is_file()


# 14: --gap-policy tolerate --max-gaps 0 -> Exit != 0, keine Output-Datei.
def test_gap_tolerate_exceeds_max_gaps(tmp_path):
    out = tmp_path / "report.md"
    rc = main(_args(_GAP_FIXTURE, out, "--gap-policy", "tolerate", "--max-gaps", "0"))
    assert rc != 0
    assert not out.exists()


# 15: --max-gaps -1 -> Exit != 0, keine Output-Datei.
def test_negative_max_gaps_fails(tmp_path):
    out = tmp_path / "report.md"
    rc = main(_args("strategy_mid_breakout_long.csv", out, "--max-gaps", "-1"))
    assert rc != 0
    assert not out.exists()
