"""Lokales CLI: MidBreakoutStrategy-Backtest -> Markdown-Report (LQ-007 Phase 2b).

Aufruf::

    python -m liquent.cli.backtest_mid_breakout --csv <PATH> --output <PATH>

Wertet eine lokale OHLCV-CSV mit ``MidBreakoutStrategy`` im ``percent_risk``-Modus
aus und schreibt einen deterministischen Markdown-Report. Reine Orchestrierung
der bestehenden Pipeline:

    HistoricalFileSource -> MidBreakoutStrategy -> RiskEngine -> BacktestRunner
    -> summarize_backtest_result -> summary_to_markdown -> Datei

Sicherheit: nur lokale Dateien, keine Netzwerk-Calls, keine Exchange-Anbindung,
keine Zugangsdaten, keine Live-/Simulationsausführung. Der Output ist
deterministisch — keine Wall-Clock-Zeit, keine Zufallswerte; gleicher Input
ergibt einen byte-identischen Report. Dies ist ein Research-/Analysewerkzeug und
trifft keine Aussage über zukünftige Ergebnisse.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from liquent.backtesting.reporting import (
    summarize_backtest_result,
    summary_to_markdown,
)
from liquent.backtesting.runner import BacktestRunner, CostModel
from liquent.data.sources import DataSourceMetadata, HistoricalFileSource
from liquent.risk.engine import RiskEngine, RiskLimits
from liquent.strategy import MidBreakoutStrategy, MidBreakoutStrategyV1

# Statischer, deterministischer Kopf des Reports (kein Zeitstempel, kein Zufall).
_DISCLAIMER = (
    "<!-- Generated by Liquent local CLI. "
    "Research/backtesting only; not investment advice. -->"
)

_TIMEFRAMES = ("1m", "5m", "15m", "1h")
_GAP_POLICIES = ("reject", "flag", "tolerate")
_HISTORY_POLICIES = ("flag", "reject", "ignore")
_STRATEGIES = ("v0", "v1")

# Strategieabhängige Defaults für gemeinsame Parameter (LQ-009 Phase 2).
# v0 behält die bisherigen CLI-Defaults (Reproduzierbarkeit bestehender Läufe);
# v1 erhält die Defaults aus MidBreakoutStrategyV1. Aufgelöst werden nur die
# vom Nutzer NICHT gesetzten (Sentinel-None-)Werte.
_V0_DEFAULTS = {"lookback_bars": 3, "stop_distance_pct": 0.05, "min_strength": 0.0}
_V1_DEFAULTS = {
    "lookback_bars": 12,
    "stop_distance_pct": 0.01,
    "min_strength": 0.0,
    "breakout_threshold_pct": 0.001,
    "cooldown_bars": 3,
}

_BOOL_TRUE = {"true", "1", "yes"}
_BOOL_FALSE = {"false", "0", "no"}

# Exit-Codes: 0 = ok, 2 = Nutzungs-/Validierungsfehler, 1 = Laufzeit-/Dateifehler.
_EXIT_OK = 0
_EXIT_RUNTIME = 1
_EXIT_USAGE = 2


def _parse_bool(value: str) -> bool:
    """Bool-Parser für ``true/false``, ``1/0``, ``yes/no`` (case-insensitive)."""
    normalized = value.strip().lower()
    if normalized in _BOOL_TRUE:
        return True
    if normalized in _BOOL_FALSE:
        return False
    raise argparse.ArgumentTypeError(
        f"ungültiger Bool-Wert: {value!r} (erlaubt: true/false, 1/0, yes/no)"
    )


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m liquent.cli.backtest_mid_breakout",
        description=(
            "Lokaler MidBreakoutStrategy-Backtest (percent_risk) -> Markdown-Report. "
            "Research/backtesting only; not investment advice."
        ),
    )
    # LQ-018: argparse argument groups nur zur Gliederung der Hilfe — KEINE
    # Änderung an Flags, Defaults, dest, choices oder Verhalten. Prozentangaben
    # in Help-Strings sind als %% escaped (argparse-Format-Platzhalter).
    g_data = parser.add_argument_group("Data input")
    g_strat = parser.add_argument_group("Strategy selection")
    g_params = parser.add_argument_group("Strategy parameters")
    g_v1 = parser.add_argument_group("Strategy v1 parameters")
    g_risk = parser.add_argument_group("Risk / Backtest")
    g_cost = parser.add_argument_group("Cost model")
    g_out = parser.add_argument_group("Output / Reporting")

    # --- Data input ---
    g_data.add_argument(
        "--csv", required=True, help="Path to the local OHLCV CSV input file."
    )
    g_data.add_argument(
        "--symbol", default="UNKNOWN", help="Instrument symbol label for report metadata."
    )
    g_data.add_argument(
        "--exchange", default="unknown", help="Exchange label for report metadata."
    )
    g_data.add_argument(
        "--asset-class", default="unknown", dest="asset_class",
        help="Asset-class label for report metadata.",
    )
    g_data.add_argument(
        "--timeframe", default="5m", choices=_TIMEFRAMES,
        help="Bar timeframe of the input data.",
    )
    g_data.add_argument(
        "--gap-policy", default="reject", choices=_GAP_POLICIES, dest="gap_policy",
        help="How to handle data gaps: reject, flag, or tolerate.",
    )
    g_data.add_argument(
        "--max-gaps", default=0, type=int, dest="max_gaps",
        help="Maximum tolerated gaps when --gap-policy tolerate (>= 0).",
    )
    g_data.add_argument(
        "--history-policy", default="flag", choices=_HISTORY_POLICIES, dest="history_policy",
        help="How to handle the minimum-history check: flag, reject, or ignore.",
    )

    # --- Strategy selection ---
    g_strat.add_argument(
        "--strategy", default="v0", choices=_STRATEGIES,
        help="Strategy version to use. Default: v0 for backward-compatible runs.",
    )

    # --- Strategy parameters (common) ---
    # Sentinel-Default None: nach dem Parsen strategieabhängig auf die v0- bzw.
    # v1-Defaults aufgelöst (Verhalten unverändert).
    g_params.add_argument(
        "--lookback-bars", default=None, type=int, dest="lookback_bars",
        help="Number of previous bars for the breakout window. "
        "Defaults depend on strategy (v0: 3, v1: 12).",
    )
    g_params.add_argument(
        "--stop-distance-pct", default=None, type=float, dest="stop_distance_pct",
        help="Relative stop distance for percent-risk sizing. The current runner "
        "uses stop_price for sizing, not as an executed stop-loss.",
    )
    g_params.add_argument(
        "--min-strength", default=None, type=float, dest="min_strength",
        help="Minimum signal strength filter. Default: 0.0.",
    )
    g_params.add_argument(
        "--allow-short", default=True, type=_parse_bool, dest="allow_short",
        help="Whether short signals are allowed (true/false). Default: true.",
    )

    # --- Strategy v1 parameters (v1-only; bei v0 hart abgelehnt) ---
    g_v1.add_argument(
        "--breakout-threshold-pct", default=None, type=float, dest="breakout_threshold_pct",
        help="Minimum relative breakout distance for v1. Only valid with --strategy v1.",
    )
    g_v1.add_argument(
        "--cooldown-bars", default=None, type=int, dest="cooldown_bars",
        help="Number of bars skipped after an emitted v1 signal. "
        "Only valid with --strategy v1.",
    )
    g_v1.add_argument(
        "--max-signals-per-day", default=None, type=int, dest="max_signals_per_day",
        help="Optional max number of v1 signals per UTC day. "
        "Only valid with --strategy v1. Omit to disable.",
    )

    # --- Risk / Backtest ---
    g_risk.add_argument(
        "--initial-equity", default=10_000.0, type=float, dest="initial_equity",
        help="Starting account equity for the backtest.",
    )
    g_risk.add_argument(
        "--risk-per-trade-pct", default=0.01, type=float, dest="risk_per_trade_pct",
        help="Risk per trade as a fraction of equity for percent-risk sizing.",
    )
    g_risk.add_argument(
        "--max-position-size", default=100.0, type=float, dest="max_position_size",
        help="Maximum position size (units) cap.",
    )
    g_risk.add_argument(
        "--max-total-exposure", default=100_000.0, type=float, dest="max_total_exposure",
        help="Maximum total exposure cap.",
    )
    g_risk.add_argument(
        "--max-daily-drawdown", default=10_000.0, type=float, dest="max_daily_drawdown",
        help="Daily drawdown limit before the risk gate pauses.",
    )

    # --- Cost model (reale CostModel-Felder; Defaults 0.0 = frictionless) ---
    g_cost.add_argument(
        "--fee-rate", default=0.0, type=float, dest="fee_rate",
        help="Fee rate as notional fraction (e.g. 0.001 = 0.1%%). Default: 0.0.",
    )
    g_cost.add_argument(
        "--spread", default=0.0, type=float, dest="spread",
        help="Absolute spread cost per unit. Default: 0.0.",
    )
    g_cost.add_argument(
        "--slippage", default=0.0, type=float, dest="slippage",
        help="Slippage as notional fraction (e.g. 0.0005 = 0.05%%). Default: 0.0.",
    )

    # --- Output / Reporting ---
    g_out.add_argument(
        "--output", required=True, help="Path of the Markdown report output."
    )
    g_out.add_argument(
        "--overwrite", action="store_true", default=False,
        help="Overwrite the output file if it already exists.",
    )
    return parser


def _resolve_strategy_args(args: argparse.Namespace) -> str | None:
    """Gating + Sentinel-Auflösung der strategieabhängigen Parameter.

    1) v1-only Parameter (``breakout_threshold_pct``, ``cooldown_bars``) bei
       ``--strategy v0`` hart ablehnen, wenn sie explizit gesetzt wurden
       (Sentinel: ``is not None``). Verhindert Scheinsicherheit.
    2) Gemeinsame Parameter (None) auf die v0- bzw. v1-Defaults auflösen.
    3) v1-only Parameter (None) auf die v1-Defaults auflösen (nur bei v1).

    Gibt eine Fehlermeldung (Usage-Fehler) zurück oder ``None``.
    """
    if args.strategy == "v0":
        if args.breakout_threshold_pct is not None:
            return "--breakout-threshold-pct ist nur mit --strategy v1 erlaubt"
        if args.cooldown_bars is not None:
            return "--cooldown-bars ist nur mit --strategy v1 erlaubt"
        if args.max_signals_per_day is not None:
            return "--max-signals-per-day ist nur mit --strategy v1 erlaubt"

    common = _V1_DEFAULTS if args.strategy == "v1" else _V0_DEFAULTS
    if args.lookback_bars is None:
        args.lookback_bars = common["lookback_bars"]
    if args.stop_distance_pct is None:
        args.stop_distance_pct = common["stop_distance_pct"]
    if args.min_strength is None:
        args.min_strength = common["min_strength"]

    if args.strategy == "v1":
        if args.breakout_threshold_pct is None:
            args.breakout_threshold_pct = _V1_DEFAULTS["breakout_threshold_pct"]
        if args.cooldown_bars is None:
            args.cooldown_bars = _V1_DEFAULTS["cooldown_bars"]
    return None


def _validate_ranges(args: argparse.Namespace) -> str | None:
    """Prüft numerische Wertebereiche; gibt eine Fehlermeldung oder ``None``.

    Läuft NACH ``_resolve_strategy_args`` (Sentinels sind dann aufgelöst). Die
    Strategie-Konstruktoren bleiben zusätzlich autoritativ (fail-safe).
    """
    if args.initial_equity <= 0.0:
        return "--initial-equity muss > 0 sein"
    if args.lookback_bars <= 0:
        return "--lookback-bars muss > 0 sein"
    if not (0.0 < args.stop_distance_pct < 1.0):
        return "--stop-distance-pct muss in (0, 1) liegen"
    if not (0.0 <= args.min_strength <= 1.0):
        return "--min-strength muss in [0, 1] liegen"
    if args.strategy == "v1":
        if not (0.0 <= args.breakout_threshold_pct < 0.1):
            return "--breakout-threshold-pct muss in [0, 0.1) liegen"
        if args.cooldown_bars < 0:
            return "--cooldown-bars muss >= 0 sein"
        if args.max_signals_per_day is not None and args.max_signals_per_day <= 0:
            return "--max-signals-per-day muss > 0 sein (oder weglassen)"
    if not (0.0 < args.risk_per_trade_pct <= 1.0):
        return "--risk-per-trade-pct muss in (0, 1] liegen"
    if args.max_position_size <= 0.0:
        return "--max-position-size muss > 0 sein"
    if args.max_total_exposure <= 0.0:
        return "--max-total-exposure muss > 0 sein"
    if args.max_daily_drawdown <= 0.0:
        return "--max-daily-drawdown muss > 0 sein"
    if args.max_gaps < 0:
        return "--max-gaps muss >= 0 sein"
    if args.fee_rate < 0.0:
        return "--fee-rate muss >= 0 sein"
    if args.spread < 0.0:
        return "--spread muss >= 0 sein"
    if args.slippage < 0.0:
        return "--slippage muss >= 0 sein"
    return None


def main(argv: list[str] | None = None) -> int:
    """Führt einen lokalen Backtest aus und schreibt den Markdown-Report.

    Liefert einen Exit-Code (0 = ok). Erwartbare Fehler werden klar auf stderr
    gemeldet, ohne Traceback.
    """
    parser = _build_parser()
    try:
        args = parser.parse_args(argv)
    except SystemExit as exc:  # argparse meldet Fehler bereits auf stderr.
        code = exc.code if isinstance(exc.code, int) else _EXIT_USAGE
        return code if code is not None else _EXIT_USAGE

    # 1a) Strategieauswahl auflösen (v1-only Gating + Sentinel-Defaults).
    strategy_error = _resolve_strategy_args(args)
    if strategy_error is not None:
        print(f"error: {strategy_error}", file=sys.stderr)
        return _EXIT_USAGE

    # 1b) Wertebereiche (nach Sentinel-Auflösung).
    range_error = _validate_ranges(args)
    if range_error is not None:
        print(f"error: {range_error}", file=sys.stderr)
        return _EXIT_USAGE

    # 2) CSV muss eine existierende Datei sein.
    csv_path = Path(args.csv)
    if not csv_path.is_file():
        print(f"error: --csv nicht gefunden oder keine Datei: {csv_path}", file=sys.stderr)
        return _EXIT_RUNTIME

    # 3) Überschreib-Policy: vor jeder Schreib-/Rechenarbeit prüfen.
    output_path = Path(args.output)
    if output_path.exists() and not args.overwrite:
        print(
            f"error: --output existiert bereits: {output_path} (--overwrite nutzen)",
            file=sys.stderr,
        )
        return _EXIT_RUNTIME

    # 4) Pipeline orchestrieren (bestehende API, kein Produktcode geändert).
    metadata = DataSourceMetadata(
        asset_class=args.asset_class,
        exchange=args.exchange,
        symbol=args.symbol,
    )
    source = HistoricalFileSource(
        str(csv_path),
        timeframe=args.timeframe,
        gap_policy=args.gap_policy,
        max_gaps=args.max_gaps,
        metadata=metadata,
        history_policy=args.history_policy,
    )
    if args.strategy == "v1":
        strategy = MidBreakoutStrategyV1(
            lookback_bars=args.lookback_bars,
            stop_distance_pct=args.stop_distance_pct,
            breakout_threshold_pct=args.breakout_threshold_pct,
            cooldown_bars=args.cooldown_bars,
            allow_short=args.allow_short,
            min_strength=args.min_strength,
            max_signals_per_day=args.max_signals_per_day,
        )
    else:
        strategy = MidBreakoutStrategy(
            lookback_bars=args.lookback_bars,
            stop_distance_pct=args.stop_distance_pct,
            min_strength=args.min_strength,
            allow_short=args.allow_short,
        )
    limits = RiskLimits(
        max_position_size=args.max_position_size,
        max_total_exposure=args.max_total_exposure,
        risk_per_trade=0.0,
        max_daily_drawdown=args.max_daily_drawdown,
        sizing_mode="percent_risk",
        risk_per_trade_pct=args.risk_per_trade_pct,
        max_position_notional=0.0,
        max_daily_loss=0.0,
        max_losing_streak=0,
    )
    runner = BacktestRunner(
        source=source,
        risk_engine=RiskEngine(limits),
        cost_model=CostModel(
            fee_rate=args.fee_rate,
            spread=args.spread,
            slippage=args.slippage,
        ),
        strategy=strategy,
        initial_equity=args.initial_equity,
    )

    try:
        result = runner.run()
    except (ValueError, TypeError) as exc:
        # z. B. CSV-Validierung, Gap-/History-Reject, ungültige Strategie-Signale.
        print(f"error: Auswertung fehlgeschlagen: {exc}", file=sys.stderr)
        return _EXIT_RUNTIME

    # LQ-011: Strategie-Metadaten aus den EFFEKTIVEN (Sentinel-aufgelösten)
    # Werten bauen — deterministische Parameter-Reihenfolge je Strategie.
    if args.strategy == "v1":
        strategy_params: dict[str, object] = {
            "lookback_bars": args.lookback_bars,
            "stop_distance_pct": args.stop_distance_pct,
            "breakout_threshold_pct": args.breakout_threshold_pct,
            "cooldown_bars": args.cooldown_bars,
            "allow_short": args.allow_short,
            "min_strength": args.min_strength,
            # LQ-015: None = deaktiviert (reproduzierbarer v1-Parameter).
            "max_signals_per_day": args.max_signals_per_day,
        }
    else:
        strategy_params = {
            "lookback_bars": args.lookback_bars,
            "stop_distance_pct": args.stop_distance_pct,
            "allow_short": args.allow_short,
            "min_strength": args.min_strength,
        }
    strategy_metadata = {
        "family": "mid_breakout",
        "key": args.strategy,
        "name": type(strategy).__name__,
        "params": strategy_params,
    }

    # LQ-012: Kosten-Metadaten aus den effektiven CLI-Werten. Immer übergeben,
    # damit der Report die Kosten (auch 0.0) explizit ausweist.
    cost_metadata = {
        "fee_rate": args.fee_rate,
        "spread": args.spread,
        "slippage": args.slippage,
    }

    summary = summarize_backtest_result(
        result,
        title="Liquent MidBreakout Backtest",
        strategy_metadata=strategy_metadata,
        cost_metadata=cost_metadata,
    )
    markdown = summary_to_markdown(summary)
    content = f"{_DISCLAIMER}\n\n{markdown}\n"

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"report written: {output_path}")
    # Minimal-invasiver Terminal-Hinweis auf die effektiv verwendete Strategie
    # (der deterministische Markdown-Report bleibt unverändert; er trägt den
    # Strategie-Klassennamen bereits über parameters["strategy"]).
    strategy_line = (
        f"strategy: {args.strategy} ({type(strategy).__name__}) "
        f"lookback_bars={args.lookback_bars} stop_distance_pct={args.stop_distance_pct} "
        f"min_strength={args.min_strength} allow_short={args.allow_short}"
    )
    if args.strategy == "v1":
        strategy_line += (
            f" breakout_threshold_pct={args.breakout_threshold_pct} "
            f"cooldown_bars={args.cooldown_bars} "
            f"max_signals_per_day={args.max_signals_per_day}"
        )
    print(strategy_line)
    print(
        f"cost_model: fee_rate={args.fee_rate} spread={args.spread} "
        f"slippage={args.slippage}"
    )
    return _EXIT_OK


if __name__ == "__main__":
    raise SystemExit(main())
